// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package repository

import (
	"github.com/ljgago/api-rest/internal/core/domain"
	"github.com/ljgago/api-rest/internal/core/port"
	"sync"
)

// Ensure, that BookRepositoryMock does implement BookRepository.
// If this is not the case, regenerate this file with moq.
var _ port.BookRepository = &BookRepositoryMock{}

// BookRepositoryMock is a mock implementation of BookRepository.
//
// 	func TestSomethingThatUsesBookRepository(t *testing.T) {
//
// 		// make and configure a mocked BookRepository
// 		mockedBookRepository := &BookRepositoryMock{
// 			CreateFunc: func(book domain.Book) (domain.Book, error) {
// 				panic("mock out the Create method")
// 			},
// 			DeleteFunc: func(id int) error {
// 				panic("mock out the Delete method")
// 			},
// 			ReadFunc: func() ([]domain.Book, error) {
// 				panic("mock out the Read method")
// 			},
// 			ReadOneFunc: func(id int) (domain.Book, error) {
// 				panic("mock out the ReadOne method")
// 			},
// 			UpdateFunc: func(id int, book domain.Book) (domain.Book, error) {
// 				panic("mock out the Update method")
// 			},
// 		}
//
// 		// use mockedBookRepository in code that requires BookRepository
// 		// and then make assertions.
//
// 	}
type BookRepositoryMock struct {
	// CreateFunc mocks the Create method.
	CreateFunc func(book domain.Book) (domain.Book, error)

	// DeleteFunc mocks the Delete method.
	DeleteFunc func(id int) error

	// ReadFunc mocks the Read method.
	ReadFunc func() ([]domain.Book, error)

	// ReadOneFunc mocks the ReadOne method.
	ReadOneFunc func(id int) (domain.Book, error)

	// UpdateFunc mocks the Update method.
	UpdateFunc func(id int, book domain.Book) (domain.Book, error)

	// calls tracks calls to the methods.
	calls struct {
		// Create holds details about calls to the Create method.
		Create []struct {
			// Book is the book argument value.
			Book domain.Book
		}
		// Delete holds details about calls to the Delete method.
		Delete []struct {
			// ID is the id argument value.
			ID int
		}
		// Read holds details about calls to the Read method.
		Read []struct {
		}
		// ReadOne holds details about calls to the ReadOne method.
		ReadOne []struct {
			// ID is the id argument value.
			ID int
		}
		// Update holds details about calls to the Update method.
		Update []struct {
			// ID is the id argument value.
			ID int
			// Book is the book argument value.
			Book domain.Book
		}
	}
	lockCreate  sync.RWMutex
	lockDelete  sync.RWMutex
	lockRead    sync.RWMutex
	lockReadOne sync.RWMutex
	lockUpdate  sync.RWMutex
}

// Create calls CreateFunc.
func (mock *BookRepositoryMock) Create(book domain.Book) (domain.Book, error) {
	if mock.CreateFunc == nil {
		panic("BookRepositoryMock.CreateFunc: method is nil but BookRepository.Create was just called")
	}
	callInfo := struct {
		Book domain.Book
	}{
		Book: book,
	}
	mock.lockCreate.Lock()
	mock.calls.Create = append(mock.calls.Create, callInfo)
	mock.lockCreate.Unlock()
	return mock.CreateFunc(book)
}

// CreateCalls gets all the calls that were made to Create.
// Check the length with:
//     len(mockedBookRepository.CreateCalls())
func (mock *BookRepositoryMock) CreateCalls() []struct {
	Book domain.Book
} {
	var calls []struct {
		Book domain.Book
	}
	mock.lockCreate.RLock()
	calls = mock.calls.Create
	mock.lockCreate.RUnlock()
	return calls
}

// Delete calls DeleteFunc.
func (mock *BookRepositoryMock) Delete(id int) error {
	if mock.DeleteFunc == nil {
		panic("BookRepositoryMock.DeleteFunc: method is nil but BookRepository.Delete was just called")
	}
	callInfo := struct {
		ID int
	}{
		ID: id,
	}
	mock.lockDelete.Lock()
	mock.calls.Delete = append(mock.calls.Delete, callInfo)
	mock.lockDelete.Unlock()
	return mock.DeleteFunc(id)
}

// DeleteCalls gets all the calls that were made to Delete.
// Check the length with:
//     len(mockedBookRepository.DeleteCalls())
func (mock *BookRepositoryMock) DeleteCalls() []struct {
	ID int
} {
	var calls []struct {
		ID int
	}
	mock.lockDelete.RLock()
	calls = mock.calls.Delete
	mock.lockDelete.RUnlock()
	return calls
}

// Read calls ReadFunc.
func (mock *BookRepositoryMock) Read() ([]domain.Book, error) {
	if mock.ReadFunc == nil {
		panic("BookRepositoryMock.ReadFunc: method is nil but BookRepository.Read was just called")
	}
	callInfo := struct {
	}{}
	mock.lockRead.Lock()
	mock.calls.Read = append(mock.calls.Read, callInfo)
	mock.lockRead.Unlock()
	return mock.ReadFunc()
}

// ReadCalls gets all the calls that were made to Read.
// Check the length with:
//     len(mockedBookRepository.ReadCalls())
func (mock *BookRepositoryMock) ReadCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockRead.RLock()
	calls = mock.calls.Read
	mock.lockRead.RUnlock()
	return calls
}

// ReadOne calls ReadOneFunc.
func (mock *BookRepositoryMock) ReadOne(id int) (domain.Book, error) {
	if mock.ReadOneFunc == nil {
		panic("BookRepositoryMock.ReadOneFunc: method is nil but BookRepository.ReadOne was just called")
	}
	callInfo := struct {
		ID int
	}{
		ID: id,
	}
	mock.lockReadOne.Lock()
	mock.calls.ReadOne = append(mock.calls.ReadOne, callInfo)
	mock.lockReadOne.Unlock()
	return mock.ReadOneFunc(id)
}

// ReadOneCalls gets all the calls that were made to ReadOne.
// Check the length with:
//     len(mockedBookRepository.ReadOneCalls())
func (mock *BookRepositoryMock) ReadOneCalls() []struct {
	ID int
} {
	var calls []struct {
		ID int
	}
	mock.lockReadOne.RLock()
	calls = mock.calls.ReadOne
	mock.lockReadOne.RUnlock()
	return calls
}

// Update calls UpdateFunc.
func (mock *BookRepositoryMock) Update(id int, book domain.Book) (domain.Book, error) {
	if mock.UpdateFunc == nil {
		panic("BookRepositoryMock.UpdateFunc: method is nil but BookRepository.Update was just called")
	}
	callInfo := struct {
		ID   int
		Book domain.Book
	}{
		ID:   id,
		Book: book,
	}
	mock.lockUpdate.Lock()
	mock.calls.Update = append(mock.calls.Update, callInfo)
	mock.lockUpdate.Unlock()
	return mock.UpdateFunc(id, book)
}

// UpdateCalls gets all the calls that were made to Update.
// Check the length with:
//     len(mockedBookRepository.UpdateCalls())
func (mock *BookRepositoryMock) UpdateCalls() []struct {
	ID   int
	Book domain.Book
} {
	var calls []struct {
		ID   int
		Book domain.Book
	}
	mock.lockUpdate.RLock()
	calls = mock.calls.Update
	mock.lockUpdate.RUnlock()
	return calls
}
